version: '2'

services:
  users:
    image: users:0.0.1-SNAPSHOT
    container_name: users
    cap_drop:
          - ALL
    volumes:
          - /home/blacklightning/dev/conf:/config:ro
          - /home/blacklightning/dev/certs:/certs:ro
    ports:
          - "6002:6002"
    depends_on:
          - postgres

  postgres:
      image: postgres
      container_name: postgresdb
      ports:
          - "5432:5432"
      environment:
          - POSTGRES_USER=root
          - POSTGRES_PASSWORD=pass123
